### ISSUE TITLE
Annotating and Opening PDFs in gDrvie

### ISSUE THREAD

**Issue by jgmac1106** [hypothesis/pdf.js-hypothes.is#6]
How do you annotate PDFs saved in gDrive. For example: https://drive.google.com/file/d/0BzYA1Z_-XipwNkpzOGl4alNPTEU/view?usp=sharing

When I click on the extension in Chrome nothing happens. gDrive is probably going to a primary way PDFs are shared in educatinional settings.

I noticed that the file does not have a pdf extension. Maybe we need to work on some documentation on how to share and then annotate files using gDrive.

**Comment by judell** [comment]
For PDFs the answer for now: download and annotate locally, in collaboration with others doing the same, as per https://hypothes.is/blog/synchronizing-annotations-between-local-and-remote-pdfs/. That's because our implementation is based on https://github.com/mozilla/pdf.js which GDrive does not use.

You annotate other doc types on GDrive, but your mileage will vary. I recommend closing this issue; I'll document those other cases elsewhere.

**Comment by jgmac1106** [comment]
Thanks John. So if user one downloads a file from gDrive, annotates
locally,  and reuploads can user two download, annotate locally and see
user one?

I might just tell teachers to download the file and host it somewhere else.
Is that better?

**Comment by csillag** [comment]
>  So if user one downloads a file from gDrive, annotates locally, and reuploads can user two download, annotate locally and see user one?

User  one doesn't even have to re-upload.

 * User one downloads annotates locally. Annotations are stored at our server.
 * User two downloads the same file, annotates locally. He will see what user one has done.

**Comment by judell** [comment]
"I might just tell teachers to download the file and host it somewhere else.
Is that better?"

If convenient that's better, you'd rather have an URL as a public rendezvous.

**Comment by jgmac1106** [comment]
Thanks all.

**Comment by hubgit** [comment]
You might be interested in [MetaPDF](https://www.metapdf.com/) from Paperpile, which uses pdf.js and annotates PDFs stored in Google Drive.
